---

volumes:
  psql-data:

services:
  mcp_sse_server:
    container_name: mcp_sse_server
    env_file:
      - .env
    image: pondered/airflow-mcp:latest
    ports:
      - 8000:8000
    restart: always
    environment:
      TRANSPORT_TYPE: sse
      POST_MODE: 'false'
      AIRFLOW_INSIGHTS_MODE: 'true'
    networks:
      data-lake-network: 

networks:
  data-lake-network: 
